/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as IncomeRouteImport } from './routes/income'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthoritiesRouteImport } from './routes/authorities'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionIdRouteImport } from './routes/transaction.$id'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeRoute = IncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoritiesRoute = AuthoritiesRouteImport.update({
  id: '/authorities',
  path: '/authorities',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIdRoute = TransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/authorities': typeof AuthoritiesRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/expense': typeof ExpenseRoute
  '/forecast': typeof ForecastRoute
  '/income': typeof IncomeRoute
  '/loans': typeof LoansRoute
  '/recurring': typeof RecurringRoute
  '/reserve': typeof ReserveRoute
  '/transactions': typeof TransactionsRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/authorities': typeof AuthoritiesRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/expense': typeof ExpenseRoute
  '/forecast': typeof ForecastRoute
  '/income': typeof IncomeRoute
  '/loans': typeof LoansRoute
  '/recurring': typeof RecurringRoute
  '/reserve': typeof ReserveRoute
  '/transactions': typeof TransactionsRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/authorities': typeof AuthoritiesRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/expense': typeof ExpenseRoute
  '/forecast': typeof ForecastRoute
  '/income': typeof IncomeRoute
  '/loans': typeof LoansRoute
  '/recurring': typeof RecurringRoute
  '/reserve': typeof ReserveRoute
  '/transactions': typeof TransactionsRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/authorities'
    | '/collections'
    | '/documents'
    | '/expense'
    | '/forecast'
    | '/income'
    | '/loans'
    | '/recurring'
    | '/reserve'
    | '/transactions'
    | '/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/authorities'
    | '/collections'
    | '/documents'
    | '/expense'
    | '/forecast'
    | '/income'
    | '/loans'
    | '/recurring'
    | '/reserve'
    | '/transactions'
    | '/transaction/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/authorities'
    | '/collections'
    | '/documents'
    | '/expense'
    | '/forecast'
    | '/income'
    | '/loans'
    | '/recurring'
    | '/reserve'
    | '/transactions'
    | '/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthoritiesRoute: typeof AuthoritiesRoute
  CollectionsRoute: typeof CollectionsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpenseRoute: typeof ExpenseRoute
  ForecastRoute: typeof ForecastRoute
  IncomeRoute: typeof IncomeRoute
  LoansRoute: typeof LoansRoute
  RecurringRoute: typeof RecurringRoute
  ReserveRoute: typeof ReserveRoute
  TransactionsRoute: typeof TransactionsRoute
  TransactionIdRoute: typeof TransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorities': {
      id: '/authorities'
      path: '/authorities'
      fullPath: '/authorities'
      preLoaderRoute: typeof AuthoritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$id': {
      id: '/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof TransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthoritiesRoute: AuthoritiesRoute,
  CollectionsRoute: CollectionsRoute,
  DocumentsRoute: DocumentsRoute,
  ExpenseRoute: ExpenseRoute,
  ForecastRoute: ForecastRoute,
  IncomeRoute: IncomeRoute,
  LoansRoute: LoansRoute,
  RecurringRoute: RecurringRoute,
  ReserveRoute: ReserveRoute,
  TransactionsRoute: TransactionsRoute,
  TransactionIdRoute: TransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
